algorithm_description: Fetch DEM tiles within a bounding box from the Copernicus
  DEM in the AWS Open Data registry, stitch them together with GDAL, create a
  single GeoTIFF DEM at 'output/dem.tif', and optionally perform intense,
  multi-core computations, profiled with the Scalene profiler.
algorithm_name: GET-DEM
algorithm_version: 0.2.0
repository_url: https://github.com/MAAP-Project/get-dem.git
docker_container_url: mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.4
disk_space: 20GB
queue: maap-dps-worker-32gb
build_command: get-dem/build-env.sh
run_command: get-dem/run.sh
inputs:
  config: []
  file: []
  positional:
  - default: ''
    description: Bounding box as LEFT BOTTOM RIGHT TOP
    name: bbox
    required: true
  - default: ''
    description: Flag to perform intense, multi-core computations
    name: compute
    required: false
  - default: ''
    description: Arguments to pass to Scalene for memory and CPU performance profiling
    name: scalene_args
    required: false
