# Input params for OGC application package generator
# The information provided in this file supports CWL and OGC best practices
algorithm_description: This is a wrapper for the sardem-sarsen algorithm to exercise the MAAP processing pipeline.
algorithm_name: get-dem
algorithm_version: mlucas/ogc
keywords: ogc, sar
code_repository: https://github.com/MAAP-Project/get-dem.git
citation: https://github.com/MAAP-Project/get-dem.git
author: mlucas
contributor: mlucas
license: https://github.com/MAAP-Project/get-dem/blob/develop/LICENSE
release_notes: None
build_command: get-dem/nasa/build-dps.sh
run_command: /app/get-dem/nasa/run.sh
ram_min: 5 # mebibytes
cores_min: 1
outdir_max: 20 # mebibytes

inputs:
  - name: bbox
    doc: Bounding box as 'LEFT BOTTOM RIGHT TOP'
    label: bounding box
    type: string
  - name: compute
    doc: Flag to perform intense, multi-core computations (any non-empty value will enable this)
    label: compute
    type: string

outputs:
  - name: out
    type: Directory
